import Head from "next/head";
import { Inter } from "next/font/google";
import { MainPage } from "./MainPage";
import React from "react";
import ReactDOM from "react-dom";
import { store } from "../redux/store/index";
import { Provider } from "react-redux";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>MyFirstAplication</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Provider store={store}>
          <React.StrictMode>
            <MainPage />
          </React.StrictMode>
        </Provider>
      </div>
    </>
  );
}
